apiVersion: apps/v1
kind: Deployment
metadata:
  name: satelite-control-deployment-7
  namespace: default
  labels:
    app: satelite-control-deployment-1
spec:
  replicas: 1 # number of pods
  selector:
    matchLabels:
      app: satelite-control-deployment-1
  template:
    metadata:
      labels:
        app: satelite-control-deployment-1
    spec:
      containers:
        - name: satelite-control-image-7
          image: gcr.io/satelitesensor/satelite-control-image-15
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP