apiVersion: apps/v1
kind: Deployment
metadata:
  name: satelite-control-deployment-2
  namespace: default
  labels:
    app: satelite-control-deployment-2
spec:
  replicas: 1 # number of pods
  selector:
    matchLabels:
      app: satelite-control-deployment-2
  template:
    metadata:
      labels:
        app: satelite-control-deployment-2
    spec:
      containers:
        - name: satelite-control-image-7
          image: IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP