apiVersion: apps/v1
kind: Deployment
metadata:
  name: satelite-control-deployment-bg-v2
  namespace: default
  labels:
    app: satelite-control-deployment-bg
    version: "v2"
spec:
  replicas: 1 # number of pods
  selector:
    matchLabels:
      app: satelite-control-deployment-bg
  strategy:
    type: RollingUpdate
    rollingUpdate:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: satelite-control-deployment-bg
        version: "v2"
    spec:
      containers:
        - name: satelite-control-image-7
          image: gcr.io/satelitesensor/satelite-control-image:V2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP