apiVersion: v1
kind: Service
metadata:
  name: satelite-control-deployment-bg
  labels:
    name: satelite-control-deployment-bg
    version: "v2"
spec:
  selector:
    app: satelite-control-deployment-bg
    version: "v2"
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000