apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: satelite-control-deployment-bg
  namespace: default
  labels:
    app: satelite-control-deployment-bg
    color: $COLOR_TEST
spec:
  replicas: 1 # number of pods
  selector:
    matchLabels:
      app: satelite-control-deployment-bg
      color: $COLOR_TEST
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: satelite-control-deployment-bg
        color: $COLOR_TEST
    spec:
      containers:
        - name: satelite-control-image-7
          image: gcr.io/satelitesensor/satelite-sensor-image-20
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: satelite-control-deployment-bg
spec:
  selector:
    app: satelite-control-deployment-bg
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000


