apiVersion: v1
kind: Service
metadata:
  name: satelite-control-deployment-b
spec:
  selector:
    app: satelite-control-deployment-b
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000