# kind: Service
# apiVersion: v1
# metadata:
#   name: mongodb-service
# spec:
#   selector:
#     app: mongo-db
#   ports:
#     - port: 27017

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb-service
spec:
  clusterIP: None
  selector:
    app: mongodb-service